# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Workflows commands (::set-output): # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

name: Test Build and Deploy ⚙🐥🚀

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_and_build:
    name: Test Build ⚙🛠

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }} 📦
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path 🐈
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 🧶
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules/.cache
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies ✨
        run: yarn install --frozen-lockfile --check-files

      - name: Run linter 👨🏻‍💻
        run: yarn lint

      - name: Run formatter 💅
        run: yarn format

      - name: Run test 🛠
        run: yarn test

      - name: Run build ⚙
        run: yarn build

      - name: Cache build ready to deploy 🚀
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
            ./package.json
            ./pm2.yml
            ./tsconfig-paths-bootstrap.js
            ./tsconfig.json
            ./yarn.lock
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

  deploy:
    name: Deploy to production ✨🚀

    needs: test_and_build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure SSH ⚙
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat <<EOF >~/.ssh/config
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/production.key
            BatchMode yes
            StrictHostKeyChecking no
          EOF

      - name: Restore build cache ♻️
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
            ./package.json
            ./pm2.yml
            ./tsconfig-paths-bootstrap.js
            ./tsconfig.json
            ./yarn.lock
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

      - name: Setup remote host ENV 🌏
        env:
          DISCORD_TOKEN: ${{ secrets.PRODUCTION_DISCORD_TOKEN }}
          DB_URI: ${{ secrets.PRODUCTION_DB_URI }}
        run: |
          cat <<EOF >./.env
          NODE_ENV=production
          DISCORD__BOT_TOKEN=$DISCORD_TOKEN
          DB_URI=$DB_URI
          PREFIX=
          EOF

      - name: Upload build state to remote host 🆙
        run: rsync -rltDvzOh --delete ./ production:${{ secrets.PRODUCTION_SSH_PATH }}

      - name: Install dependencies in remote host ✨
        run: ssh production 'cd ${{ secrets.PRODUCTION_SSH_PATH }} && yarn --production --check-files'

      - name: Run Emperor Ruppy 🐥
        run: ssh production 'if pm2 describe emperor-ruppy; then pm2 restart emperor-ruppy; else cd ${{ secrets.PRODUCTION_SSH_PATH }} && yarn start; fi'
